export const rolePermissions = {
  SUPER_ADMIN: ["ALL"],

  OWNER: [
    "CREATE_PROJECT",
    "UPDATE_PROJECT",
    "DELETE_PROJECT",
    "MANAGE_USERS",
    "CREATE_TASK",
    "UPDATE_TASK",
    "DELETE_TASK",
    "SEND_MESSAGE",
    "UPDATE_MEMBER_ROLE",
    "CREATE_GROUP_CHAT",
    "ADD_MEMBER",
    "REMOVE_MEMBER",
    "ARCHIVE_PROJECT",
    "UNARCHIVE_PROJECT",
    "READ_PROJECT",
    "READ_TASK",
    "READ_GROUP_CHAT",
    "READ_MESSAGE",
    "READ_MEMBER",
    "READ_PROJECT_MEMBER",
    "READ_TASK_MEMBER",
    "READ_GROUP_CHAT_MEMBER",
    "READ_MESSAGE_MEMBER",
    "READ_PROJECT_MEMBER",
    "READ_TASK_MEMBER",
    "READ_GROUP_CHAT_MEMBER",
    "READ_MESSAGE_MEMBER",
  ],

  ADMIN: [
    "CREATE_PROJECT",
    "UPDATE_PROJECT",
    "CREATE_TASK",
    "UPDATE_TASK",
    "DELETE_TASK",
    "SEND_MESSAGE",
    "CREATE_GROUP_CHAT",
  ],

  MANAGER: ["CREATE_PROJECT", "CREATE_TASK", "UPDATE_TASK", "SEND_MESSAGE"],

  USER: ["CREATE_TASK", "UPDATE_TASK", "SEND_MESSAGE", "LEAVE_PROJECT"],

  VIEWER: ["SEND_MESSAGE", "LEAVE_PROJECT"],
};
